### ISSUE TITLE
A bug while setting weight_factor

### ISSUE THREAD

**Issue by memray** [Diego999/py-rouge#10]
Hi @Diego999 ,

I found that if I set a different `weight_factor`, say change it from 1.0 to 1.2, both rouge-l and rouge-w will change. And the rouge-l given w=1.2 is hugely different from perl version, but with w=1.0 it's close. If I understand correctly, this behavior should cause no effect to rouge-l (no reweighting). I guess it's a bug in rouge-l implementation, though I haven't located the error.

And I was trying to compare the score of your implementation with the Perl version. Per my observation, the scores are very similar (I can see slight differences). Good implementation!

Thanks,
Rui

**Comment by memray** [comment]
Change line 614 and line 625
from `score = Rouge._compute_p_r_f_score(total_hypothesis_ngrams_count, total_reference_ngrams_count, total_ngrams_overlapping_count, self.alpha, self.weight_factor)`
to `score = Rouge._compute_p_r_f_score(total_hypothesis_ngrams_count, total_reference_ngrams_count, total_ngrams_overlapping_count, self.alpha, self.weight_factor if use_w else 1.0)`

will fix it.

**Comment by diegoantognini** [comment]
Hi @memray 

Thank you for your message. A pull request is welcome :-)

**Comment by diegoantognini** [comment]
thanks !
