### ISSUE TITLE
Is this implementation correct?

### ISSUE THREAD

**Issue by bckim92** [Diego999/py-rouge#2]
Hello,

Thank you for your full python implementation version of the ROUGE metric.
But I found a weird thing when I use your ROUGE evaluator.
To the best of my knowledge, by the definition, ROUGE-L has the property that its value is less than or equal to unigram F-measure.
However, in the example result of the README, ROUGE-L is higher than ROUGE-1 in all the measures. (and the same thing happens when I use it in my project.)
I think there may be some error in your implementation.
Can you check it for me? or maybe we can find it together.

Thank you

**Comment by diegoantognini** [comment]
Hi,

Thank you for the issue. Well, unit test ensures that values obtained via the python code is similar that the ones produces by the perl script. If the perl script is producing higher ROUGE-L, well it should be correct. Could you do the test with the pyrouge for example ?

Don't forget that ROUGE-L is not just the LCS of a text but depends on the LCS of each sentence.

**Comment by demdecuong** [comment]
Please open this problem
I have test my summary with rouge(https://pypi.org/project/rouge/) and rouge-score(https://pypi.org/project/rouge-score/) and they give my rouge-l < r1 which is fair enough.
While the py-rouge makes the rouge-l higher than r-1 which is not correct in my case.

I think there might be some bugs. 
pyrouge :  38.91 | 16.64 | 39.58
rouge :  37.71 | 16.16  | 36.54
rouge-score :  38.55 | 16.56 | 26.45
