### ISSUE TITLE
Different Lines of Text in Hypothesis Summary and Reference Summary

### ISSUE THREAD

**Issue by SophiaHan6** [Diego999/py-rouge#4]
Hi, 

Thank you for your work!
When the hypothesis summary and reference summary does not have same number of lines of text, how should ROUGE-L be calculated?

Thanks!
Shirley

**Comment by diegoantognini** [comment]
Hi,

I suggest you to read the original paper ;-)

Cheers

**Comment by SophiaHan6** [comment]
I looked at the original paper and found it out! Thanks!
